UPDATE APP.ENDPOINT
SET RULEBANTIMEINSECONDS = 0,
    RULEIPBASED = false,
    RULEPERMANENTBAN = false,
    RULEREQUESTLIMITCOUNT = 0,
    RULESTATUS = 'NOT_CONFIGURED',
    RULETIMELIMITINSECONDS = 0
WHERE FQCN = 'org.easypeelsecurity.springdogtest.ExampleController.example3';

UPDATE APP.ENDPOINT
SET RULEBANTIMEINSECONDS = 3600,
    RULEIPBASED = true,
    RULEPERMANENTBAN = false,
    RULEREQUESTLIMITCOUNT = 100,
    RULESTATUS = 'ACTIVE',
    RULETIMELIMITINSECONDS = 600
WHERE FQCN = 'org.easypeelsecurity.springdogtest.ExampleController.example2';

UPDATE APP.ENDPOINT
SET RULEBANTIMEINSECONDS = 0,
    RULEIPBASED = true,
    RULEPERMANENTBAN = false,
    RULEREQUESTLIMITCOUNT = 0,
    RULESTATUS = 'NOT_CONFIGURED',
    RULETIMELIMITINSECONDS = 0
WHERE FQCN = 'org.easypeelsecurity.springdogtest.ExampleController.example5';

UPDATE APP.ENDPOINT
SET RULEBANTIMEINSECONDS = 3600,
    RULEIPBASED = true,
    RULEPERMANENTBAN = false,
    RULEREQUESTLIMITCOUNT = 100,
    RULESTATUS = 'ACTIVE',
    RULETIMELIMITINSECONDS = 600
WHERE FQCN = 'org.easypeelsecurity.springdogtest.ExampleController.example4';

UPDATE APP.ENDPOINT
SET RULEBANTIMEINSECONDS = 3600,
    RULEIPBASED = true,
    RULEPERMANENTBAN = false,
    RULEREQUESTLIMITCOUNT = 100,
    RULESTATUS = 'ACTIVE',
    RULETIMELIMITINSECONDS = 600
WHERE FQCN = 'org.easypeelsecurity.springdogtest.ExampleController.example';
