package org.easypeelsecurity.springdog.domain.statistics.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

/**
 * Class _SystemMetric was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SystemMetric extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final NumericProperty<Double> CPU_USAGE_PERCENT = PropertyFactory.createNumeric("cpuUsagePercent", Double.class);
    public static final NumericProperty<Double> DISK_USAGE_PERCENT = PropertyFactory.createNumeric("diskUsagePercent", Double.class);
    public static final NumericProperty<Long> ID = PropertyFactory.createNumeric("id", Long.class);
    public static final NumericProperty<Double> JVM_HEAP_USAGE_PERCENT = PropertyFactory.createNumeric("jvmHeapUsagePercent", Double.class);
    public static final NumericProperty<Double> JVM_NON_HEAP_USAGE_PERCENT = PropertyFactory.createNumeric("jvmNonHeapUsagePercent", Double.class);
    public static final NumericProperty<Long> JVM_TOTAL_MEMORY_USED = PropertyFactory.createNumeric("jvmTotalMemoryUsed", Long.class);
    public static final StringProperty<String> MEMO = PropertyFactory.createString("memo", String.class);
    public static final NumericProperty<Double> MEMORY_USAGE_PERCENT = PropertyFactory.createNumeric("memoryUsagePercent", Double.class);
    public static final NumericProperty<Long> NETWORK_IN_BYTES = PropertyFactory.createNumeric("networkInBytes", Long.class);
    public static final NumericProperty<Long> NETWORK_OUT_BYTES = PropertyFactory.createNumeric("networkOutBytes", Long.class);
    public static final DateProperty<LocalDateTime> TIMESTAMP = PropertyFactory.createDate("timestamp", LocalDateTime.class);

    protected double cpuUsagePercent;
    protected double diskUsagePercent;
    protected long id;
    protected double jvmHeapUsagePercent;
    protected double jvmNonHeapUsagePercent;
    protected long jvmTotalMemoryUsed;
    protected String memo;
    protected double memoryUsagePercent;
    protected long networkInBytes;
    protected long networkOutBytes;
    protected LocalDateTime timestamp;


    public void setCpuUsagePercent(double cpuUsagePercent) {
        beforePropertyWrite("cpuUsagePercent", this.cpuUsagePercent, cpuUsagePercent);
        this.cpuUsagePercent = cpuUsagePercent;
    }

    public double getCpuUsagePercent() {
        beforePropertyRead("cpuUsagePercent");
        return this.cpuUsagePercent;
    }

    public void setDiskUsagePercent(double diskUsagePercent) {
        beforePropertyWrite("diskUsagePercent", this.diskUsagePercent, diskUsagePercent);
        this.diskUsagePercent = diskUsagePercent;
    }

    public double getDiskUsagePercent() {
        beforePropertyRead("diskUsagePercent");
        return this.diskUsagePercent;
    }

    public void setId(long id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public long getId() {
        beforePropertyRead("id");
        return this.id;
    }

    public void setJvmHeapUsagePercent(double jvmHeapUsagePercent) {
        beforePropertyWrite("jvmHeapUsagePercent", this.jvmHeapUsagePercent, jvmHeapUsagePercent);
        this.jvmHeapUsagePercent = jvmHeapUsagePercent;
    }

    public double getJvmHeapUsagePercent() {
        beforePropertyRead("jvmHeapUsagePercent");
        return this.jvmHeapUsagePercent;
    }

    public void setJvmNonHeapUsagePercent(double jvmNonHeapUsagePercent) {
        beforePropertyWrite("jvmNonHeapUsagePercent", this.jvmNonHeapUsagePercent, jvmNonHeapUsagePercent);
        this.jvmNonHeapUsagePercent = jvmNonHeapUsagePercent;
    }

    public double getJvmNonHeapUsagePercent() {
        beforePropertyRead("jvmNonHeapUsagePercent");
        return this.jvmNonHeapUsagePercent;
    }

    public void setJvmTotalMemoryUsed(long jvmTotalMemoryUsed) {
        beforePropertyWrite("jvmTotalMemoryUsed", this.jvmTotalMemoryUsed, jvmTotalMemoryUsed);
        this.jvmTotalMemoryUsed = jvmTotalMemoryUsed;
    }

    public long getJvmTotalMemoryUsed() {
        beforePropertyRead("jvmTotalMemoryUsed");
        return this.jvmTotalMemoryUsed;
    }

    public void setMemo(String memo) {
        beforePropertyWrite("memo", this.memo, memo);
        this.memo = memo;
    }

    public String getMemo() {
        beforePropertyRead("memo");
        return this.memo;
    }

    public void setMemoryUsagePercent(double memoryUsagePercent) {
        beforePropertyWrite("memoryUsagePercent", this.memoryUsagePercent, memoryUsagePercent);
        this.memoryUsagePercent = memoryUsagePercent;
    }

    public double getMemoryUsagePercent() {
        beforePropertyRead("memoryUsagePercent");
        return this.memoryUsagePercent;
    }

    public void setNetworkInBytes(long networkInBytes) {
        beforePropertyWrite("networkInBytes", this.networkInBytes, networkInBytes);
        this.networkInBytes = networkInBytes;
    }

    public long getNetworkInBytes() {
        beforePropertyRead("networkInBytes");
        return this.networkInBytes;
    }

    public void setNetworkOutBytes(long networkOutBytes) {
        beforePropertyWrite("networkOutBytes", this.networkOutBytes, networkOutBytes);
        this.networkOutBytes = networkOutBytes;
    }

    public long getNetworkOutBytes() {
        beforePropertyRead("networkOutBytes");
        return this.networkOutBytes;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        beforePropertyWrite("timestamp", this.timestamp, timestamp);
        this.timestamp = timestamp;
    }

    public LocalDateTime getTimestamp() {
        beforePropertyRead("timestamp");
        return this.timestamp;
    }

    protected abstract void onPostAdd();

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "cpuUsagePercent":
                return this.cpuUsagePercent;
            case "diskUsagePercent":
                return this.diskUsagePercent;
            case "id":
                return this.id;
            case "jvmHeapUsagePercent":
                return this.jvmHeapUsagePercent;
            case "jvmNonHeapUsagePercent":
                return this.jvmNonHeapUsagePercent;
            case "jvmTotalMemoryUsed":
                return this.jvmTotalMemoryUsed;
            case "memo":
                return this.memo;
            case "memoryUsagePercent":
                return this.memoryUsagePercent;
            case "networkInBytes":
                return this.networkInBytes;
            case "networkOutBytes":
                return this.networkOutBytes;
            case "timestamp":
                return this.timestamp;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "cpuUsagePercent":
                this.cpuUsagePercent = val == null ? 0 : (double)val;
                break;
            case "diskUsagePercent":
                this.diskUsagePercent = val == null ? 0 : (double)val;
                break;
            case "id":
                this.id = val == null ? 0 : (long)val;
                break;
            case "jvmHeapUsagePercent":
                this.jvmHeapUsagePercent = val == null ? 0 : (double)val;
                break;
            case "jvmNonHeapUsagePercent":
                this.jvmNonHeapUsagePercent = val == null ? 0 : (double)val;
                break;
            case "jvmTotalMemoryUsed":
                this.jvmTotalMemoryUsed = val == null ? 0 : (long)val;
                break;
            case "memo":
                this.memo = (String)val;
                break;
            case "memoryUsagePercent":
                this.memoryUsagePercent = val == null ? 0 : (double)val;
                break;
            case "networkInBytes":
                this.networkInBytes = val == null ? 0 : (long)val;
                break;
            case "networkOutBytes":
                this.networkOutBytes = val == null ? 0 : (long)val;
                break;
            case "timestamp":
                this.timestamp = (LocalDateTime)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeDouble(this.cpuUsagePercent);
        out.writeDouble(this.diskUsagePercent);
        out.writeLong(this.id);
        out.writeDouble(this.jvmHeapUsagePercent);
        out.writeDouble(this.jvmNonHeapUsagePercent);
        out.writeLong(this.jvmTotalMemoryUsed);
        out.writeObject(this.memo);
        out.writeDouble(this.memoryUsagePercent);
        out.writeLong(this.networkInBytes);
        out.writeLong(this.networkOutBytes);
        out.writeObject(this.timestamp);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.cpuUsagePercent = in.readDouble();
        this.diskUsagePercent = in.readDouble();
        this.id = in.readLong();
        this.jvmHeapUsagePercent = in.readDouble();
        this.jvmNonHeapUsagePercent = in.readDouble();
        this.jvmTotalMemoryUsed = in.readLong();
        this.memo = (String)in.readObject();
        this.memoryUsagePercent = in.readDouble();
        this.networkInBytes = in.readLong();
        this.networkOutBytes = in.readLong();
        this.timestamp = (LocalDateTime)in.readObject();
    }

}
