package org.easypeelsecurity.springdog.domain.ratelimit.model.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.easypeelsecurity.springdog.domain.ratelimit.model.EndpointChangelog;

/**
 * Class _EndpointVersionControl was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EndpointVersionControl extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String DATEOFVERSION_PK_COLUMN = "DATEOFVERSION";

    public static final DateProperty<LocalDateTime> DATE_OF_VERSION = PropertyFactory.createDate("dateOfVersion", LocalDateTime.class);
    public static final StringProperty<String> FULL_HASH_OF_ENDPOINTS = PropertyFactory.createString("fullHashOfEndpoints", String.class);
    public static final NumericProperty<Long> ID = PropertyFactory.createNumeric("id", Long.class);
    public static final ListProperty<EndpointChangelog> CHANGELOGS = PropertyFactory.createList("changelogs", EndpointChangelog.class);

    protected LocalDateTime dateOfVersion;
    protected String fullHashOfEndpoints;
    protected long id;

    protected Object changelogs;

    public void setDateOfVersion(LocalDateTime dateOfVersion) {
        beforePropertyWrite("dateOfVersion", this.dateOfVersion, dateOfVersion);
        this.dateOfVersion = dateOfVersion;
    }

    public LocalDateTime getDateOfVersion() {
        beforePropertyRead("dateOfVersion");
        return this.dateOfVersion;
    }

    public void setFullHashOfEndpoints(String fullHashOfEndpoints) {
        beforePropertyWrite("fullHashOfEndpoints", this.fullHashOfEndpoints, fullHashOfEndpoints);
        this.fullHashOfEndpoints = fullHashOfEndpoints;
    }

    public String getFullHashOfEndpoints() {
        beforePropertyRead("fullHashOfEndpoints");
        return this.fullHashOfEndpoints;
    }

    public void setId(long id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public long getId() {
        beforePropertyRead("id");
        return this.id;
    }

    public void addToChangelogs(EndpointChangelog obj) {
        addToManyTarget("changelogs", obj, true);
    }

    public void removeFromChangelogs(EndpointChangelog obj) {
        removeToManyTarget("changelogs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<EndpointChangelog> getChangelogs() {
        return (List<EndpointChangelog>)readProperty("changelogs");
    }

    protected abstract void onPrePersist();

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "dateOfVersion":
                return this.dateOfVersion;
            case "fullHashOfEndpoints":
                return this.fullHashOfEndpoints;
            case "id":
                return this.id;
            case "changelogs":
                return this.changelogs;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "dateOfVersion":
                this.dateOfVersion = (LocalDateTime)val;
                break;
            case "fullHashOfEndpoints":
                this.fullHashOfEndpoints = (String)val;
                break;
            case "id":
                this.id = val == null ? 0 : (long)val;
                break;
            case "changelogs":
                this.changelogs = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.dateOfVersion);
        out.writeObject(this.fullHashOfEndpoints);
        out.writeLong(this.id);
        out.writeObject(this.changelogs);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.dateOfVersion = (LocalDateTime)in.readObject();
        this.fullHashOfEndpoints = (String)in.readObject();
        this.id = in.readLong();
        this.changelogs = in.readObject();
    }

}
