springdog:
  agent:
    basePath: custom-base-path
    username: custom-username
    password: custom-password
    externalAccess: true
  system-watch:
    cpuThreshold: 11.1
  notification:
    gmail:
      enabled: false
      username: asd
      password: asd
#
#logging:
#  level:
#    root: debug
