name: "Build & Test"
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'PENEKhun/springdog' }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and test with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build test -i -xCheck

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: '**/build/reports/'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: springdog/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          fail_ci_if_error: true
